### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ulvida** [systemli/ansible-role-bind9#2]
With ansible 2.7, I have a deprecation warning: 
```
TASK [systemli.bind9 : install bind9 packages] ****************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply
 multiple items and specifying `pkg: {{ item }}`, please use `pkg: [u'bind9', u'dnsutils', u'haveged']` and remove the loop. This 
feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
The ansible code of the task would better be: 
```
- name: install bind9 packages
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
    - bind9
    - dnsutils
    - haveged
```
